### PR TITLE
Skip the flaky test: testGetsWorkingGroupLens

### PR DESCRIPTION
**Pull request by mkondratek**
Opens https://linear.app/sourcegraph/issue/CODY-2665/fix-flaky-test-testgetsworkinggrouplens.
Opens https://linear.app/sourcegraph/issue/CODY-2667/fix-flaky-test-testundo.

## Test plan
1. Green CI

### CODE REVIEW

**Comment by pkukielka** [comment]
I think they all are flaky, at least I have seen undo test failing as well. 
Is there anything specific about this one that you want to skip only it?

**Comment by mkondratek** [comment]
> I think they all are flaky, at least I have seen undo test failing as well. Is there anything specific about this one that you want to skip only it?

I want to skip all flaky tests. Do you have an example of a run with undo test failure?

**Comment by pkukielka** [comment]
> > I think they all are flaky, at least I have seen undo test failing as well. Is there anything specific about this one that you want to skip only it?
> 
> I want to skip all flaky tests. Do you have an example of a run with undo test failure?

https://github.com/sourcegraph/jetbrains/actions/runs/9712168597/job/26806362663

**Comment by odisseus** [comment]
Here's a test run in which four tests fail. The [PR](https://github.com/sourcegraph/jetbrains/pull/1819) doesn't touch the plugin code at all.
https://github.com/sourcegraph/jetbrains/actions/runs/9681170872/job/26711117391?pr=1819

**Review by pkukielka — APPROVED** [review]
LGTM, but let's create issue to fix it

**Comment by mkondratek** [comment]
> Here's a test run in which four tests fail. The [PR](https://github.com/sourcegraph/jetbrains/pull/1819) doesn't touch the plugin code at all. https://github.com/sourcegraph/jetbrains/actions/runs/9681170872/job/26711117391?pr=1819

@odisseus, it was before https://github.com/sourcegraph/jetbrains/pull/1829. Now we have seen only the mentioned two failing.

**Pull request merged**
