### PR TITLE
Bump Cody to latest main with recent context-related fixes

### PR DESCRIPTION
**Pull request by exigow**
This bump contains: https://github.com/sourcegraph/cody/pull/2211

### CODE REVIEW

**Comment by exigow** [comment]
This commit requires extensive testing due to the risk of unexpected regression from Cody agent. 

I'm currently testing it, but if anyone has some spare time, they could also take a look and possibly confirm.

**Review by mkondratek — APPROVED** [review]

**Comment by exigow** [comment]
I encountered some issues with **recipes**. 

Launching any recipe freezes the chat and outputs:

```txt
2023-12-11 16:28:49,096 [  31563]   WARN - #c.s.c.a.CodyAgent - recipe failed Error: Not implemented
2023-12-11 16:28:49,096 [  31563]   WARN - #c.s.c.a.CodyAgent -     at AgentEditor.showWarningMessage (/snapshot/dist/agent.js)
2023-12-11 16:28:49,096 [  31563]   WARN - #c.s.c.a.CodyAgent -     at ExplainCodeDetailed.getInteraction (/snapshot/dist/agent.js)
2023-12-11 16:28:49,096 [  31563]   WARN - #c.s.c.a.CodyAgent -     at Object.executeRecipe (/snapshot/dist/agent.js)
2023-12-11 16:28:49,096 [  31563]   WARN - #c.s.c.a.CodyAgent -     at /snapshot/dist/agent.js
2023-12-11 16:28:49,096 [  31563]   WARN - #c.s.c.a.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Chat hangs and you have to reset the current conversation and everything goes back to normal.

This issue **persists also on main**, so it seems to be unrelated to the recent version bump. This regression must have appeared earlier.

**Comment by exigow** [comment]
Issues with recipes seems to be unrelated with this Cody bump.

**Comment by exigow** [comment]
https://github.com/sourcegraph/jetbrains/issues/177 created.

**Pull request merged**
