### PR TITLE
Fix the appearance of `Insert at Cursor` and `Copy` buttons

### LINKED ISSUE #29: JetBrains: Button "Copy text" from chat is partially hidden and has issues with transparency
## Steps to reproduce

* Ask Cody to generate code block (for example: "simplify this code").
* Hover generated code block with mouse. 
* Button are now visible.
* Notice that buttons have issues with transparency and positioning.

## Screenshot

issue

## Additional notes

Plugin version: `5.2.1734-nightly`, but it looks like problem exists in older commits.

Tested on Linux with X11. I'm not sure if this transparency issue occurs on other OS-es.

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes https://github.com/sourcegraph/jetbrains/issues/29

## Test plan
1. `runIde` with these changes
2. go to the chat
3. ask Cody about smth that will generate a snipper (e.g. "write an example of string -> int method")

### CODE REVIEW

**Comment by mkondratek** [comment]
image


## Demo 

https://github.com/sourcegraph/jetbrains/assets/19799111/41e69479-47b8-4bbe-8249-804c70b3e0d1

**Comment by Sa1to** [comment]
Seems like font color has changed, it is less vivd 
Screenshot 2023-11-17 at 10 37 29
Screenshot 2023-11-17 at 10 37 37

**Comment by mkondratek** [comment]
Screenshot 2023-11-16 at 20 27 49

**Review by Sa1to — APPROVED** [review]
LGTM

**Comment by exigow** [comment]
LGTM :+1:

Thanks for looking on this! We can close https://github.com/sourcegraph/jetbrains/issues/29 after merging this PR.

**Review by exigow — APPROVED** [review]

**Pull request merged**
