### PR TITLE
Prefill GitHub Issue Template automatically

### PR DESCRIPTION
**Pull request by exigow**
Related to #645

This PR modifies the way users can report bugs from within the IDE. Instead of creating a new, prefilled but default issue, we now use a `report_bug.yaml` template. This gives us several cool features.

From now on, users cannot smash the "Open GitHub Issue" button because an additional input are required: description and steps to repro. This will increase the quality of our reports.
Bugs reported manually and automatically now have an identical structure.

Additional notes:
* I simplified the template because some text was redundant/noise.
* I removed the tests because the way we generate Markdown is now tightly coupled with rest of the code.

## Test Plan

* Invoke error (eg place error("") somewhere in code)
* Use Open GitHub Issue
* Browser opens on "JetBrains Bug report"
* Verify: 
  * Labels are prefilled with "bug" and "team/jetbrains"
  * Project is prefilled "sourcegraph/381" (AKA JetBrains Project)
  * Logs are prefilled with a stacktrace (and optional "additional info")
  * Versions are prefilled with IDE and plugin version

### CODE REVIEW

**Comment by exigow** [comment]
Note: It can't be tested until we merge the changes in the template to main (because we need attribute ids), but I can confirm that it works (I created a test repo for this purpose and made sure that the labels and project are correctly assigned).

**Comment by exigow** [comment]
Based on: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query

**Comment by exigow** [comment]
Note: I couldn't find a way to get a string similar to the Help->About->Copy and Close option (in reasonable time, I still believe it's accessible somewhere in API).

**Review by pkukielka — APPROVED** [review]
LGTM, but I haven't tested locally yet

**Comment by exigow** [comment]
We need to merge this into the main first to be able to check if the reporting works. 

I am merging now and will let you know soon if it's OK.

**Pull request merged**
