### PR TITLE
Add some user facing notifications

### PR DESCRIPTION
**Pull request by RXminuS**
Fixes [#359](https://github.com/sourcegraph/cody-issues/issues/359)

CleanShot 2024-05-26 at 02 02 02@2x

Could be made nicer by automatically removing the notification when the agent starts...but that seems overkill at this point.

## Test plan
- Manually verified that if the agent isn't running we show the notification

### CODE REVIEW

**Review by pkukielka — APPROVED** [review]
LGTM

**Comment by pkukielka** [comment]
CC @danielmarquespt

**Review by steveyegge — APPROVED** [review]
Looks good -- I'll merge and test it thoroughly.

**Review by aramaraju — COMMENTED** [review]
Thank you @RXminuS  - looks great!

**Pull request merged**
