### PR TITLE
Small improvements to the CI workflow

### PR DESCRIPTION
**Pull request by odisseus**
This is a follow-up to #1837.

## Test plan

Green CI

### CODE REVIEW

**Review by pkukielka — APPROVED** [review]
LGTM

**Comment by mkondratek** [comment]
https://github.com/orgs/community/discussions/26698#discussioncomment-3252954

It looks like the branch protection rule must be updated now.

**Comment by olafurpg** [comment]
Can you force push an empty commit? I just removed the branch protection rule for "JetBrains Tests". Once this PR is merged, I can add the new name to the protection rule

**Comment by odisseus** [comment]
Bumped

**Pull request merged**
