### PR TITLE
Use LogicalPosition for calculating selection range instead VisualPosition

### LINKED ISSUE #69: JetBrains: "explain selected code" does not correctly reflect the selection
Reported in https://sourcegraph.slack.com/archives/C059N5FRYG3/p1698264046869589

Steps to reproduce:

- See https://www.loom.com/share/defdeb5f1b054a5ab3a8003b33cd4396?sid=56a3d868-363c-4ff1-b442-782363e3804c
- Write a function A with 5 lines code of code
- Select the code in function B below A that also has 5 lines of code
- Trigger recipe "explain selected code"
- Cody explains function A instead of function B

### PR DESCRIPTION
**Pull request by exigow**
Fixes: https://github.com/sourcegraph/jetbrains/issues/69

Additional changes: Remove unused EditorContext Java code.

Test plan:

1. Run IDE.
2. Open any code that contains some imports and methods.
3. Collapse methods visually using Ctrl + Shift + Minus.
4. View logs with `tail -f build/sourcegraph/cody-agent-trace.json`.
5. Verify that we are sending the correct selection on textDocument/didChange call.

NOTE: line position is counted from 0, not from 1.

### CODE REVIEW

**Comment by mkondratek** [comment]
I know. It's WIP, but...
image
fixes like this are the best 😅

**Comment by exigow** [comment]
> I know. It's WIP, but... image fixes like this are the best 😅

Yeah, I was looking for where we send those caret positions and I stumbled upon some old Java code. Boy Scouting Rule. :smile: :broom:

**Comment by Strum355** [comment]
> A caret's Visual Position differs from Logical Position in that it takes into account editor presentation settings such as Code Folding and Soft Line Wrap. In doing so, [VisualPosition](https://github.com/JetBrains/intellij-community/tree/idea/232.10203.10/platform/editor-ui-api/src/com/intellij/openapi/editor/VisualPosition.java) counts - zero-based - the lines of a Document that can be displayed in an Editor. Consequently, Visual Positions can't be uniquely mapped to Logical Positions or corresponding lines in the underlying Document.

Interesting! Do you know what constructs specifically were causing the offsets in the original bug reports? :slightly_smiling_face:

**Review by Strum355 — APPROVED** [review]

**Comment by exigow** [comment]
> > A caret's Visual Position differs from Logical Position in that it takes into account editor presentation settings such as Code Folding and Soft Line Wrap. In doing so, [VisualPosition](https://github.com/JetBrains/intellij-community/tree/idea/232.10203.10/platform/editor-ui-api/src/com/intellij/openapi/editor/VisualPosition.java) counts - zero-based - the lines of a Document that can be displayed in an Editor. Consequently, Visual Positions can't be uniquely mapped to Logical Positions or corresponding lines in the underlying Document.
> 
> Interesting! Do you know what constructs specifically were causing the offsets in the original bug reports? 🙂

Import statements :sweat_smile:, which are collapsed by default, but it was hard to notice the error because it's usually just a few lines.

**Pull request merged**
