### PR TITLE
Update codyCommit

### LINKED ISSUE #191: A killing-agent error on autocompletion accept
Reported by @vdavid.

```
java.lang.RuntimeException: Cannot invoke (class=, method=afterAction, topic=Sourcegraph Cody + Code Search plugin settings have changed)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
	at jdk.proxy11/jdk.proxy11.$Proxy292.afterAction(Unknown Source)
	at com.sourcegraph.cody.config.ui.AccountConfigurable.apply(AccountConfigurable.kt:114)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.apply(ConfigurableWrapper.java:191)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor.apply(ConfigurableEditor.java:322)
	at com.intellij.openapi.options.newEditor.SettingsEditor$5.apply(SettingsEditor.java:206)
	at com.intellij.openapi.options.newEditor.SettingsEditor.apply(SettingsEditor.java:433)
	at com.intellij.openapi.options.newEditor.SettingsDialog.applyAndClose(SettingsDialog.java:201)
	at com.intellij.openapi.options.newEditor.SettingsDialog.doOKAction(SettingsDialog.java:193)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1864)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1818)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.lambda$show$2(Dialog.java:1081)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2164)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1041)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:737)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:462)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1643)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:104)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.initMacApplication$lambda$2$lambda$1(MacOSApplicationProvider.kt:71)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.submit$lambda$6(MacOSApplicationProvider.kt:170)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: GraphQLAPIClientConfig is not set
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.CodyToolWindowContent.addSubscriptionTab(CodyToolWindowContent.kt:124)
	at com.sourcegraph.cody.CodyToolWindowContent.refreshSubscriptionTab(CodyToolWindowContent.kt:148)
	at com.sourcegraph.cody.CodyToolWindowContent.refreshPanelsVisibility(CodyToolWindowContent.kt:279)
	at com.sourcegraph.cody.config.notification.AccountSettingChangeListener$1.afterAction(AccountSettingChangeListener.kt:48)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:659)
	... 114 more
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: GraphQLAPIClientConfig is not set
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by mkondratek**
Resolves https://github.com/sourcegraph/jetbrains/issues/191.

New commits to the agent:
```
Handle connection close events with no prior errors or messages (#2391)
Hide LLM dropdown for enterprise users (#2393)
Chat: Honor enterprise token limits (#2395)
Update "Start New Chat" button label casing (#2385)
set more conservative limit for gpt-3.5-turbo to stay under window limit (#2386)
VS Code: Release 1.0.0 (#2377)
Update Marketplace README with new gifs, free/pro info, and NLS (#2357)
HACK: Work around rate limiting errors by parsing the SSE message and reverse-engineering the headers (#2375)
chat: display CTA to create new chat when context limit reached (#2374)
Chat: Re-add /edit and /doc commands (#2373)
Autocomplete: format completions on accept (#2327)
Update rate limit error messages for Cody Pro users (#2364)
Chat: use the correct user tier in the upsell event (#2372)
set context window limit by model (#2371)
Chat: send `openLLMDropdown:clicked` only on dropdown open (#2370)
docs: update dev docs to include `pnpm build` (#2369)
Embeddings: Display accurate percent done; do not toast continued embeddings failure (#2368)
Fix code smell icon (#2367)
Chat: Add Mixtral as a chat model (#2307)
VSCode: Roll cody-engine to v5.2.12792 (#2359)
docs: update docs to new url (#2283)
VSCode: Fix local embeddings e2e test to specifically check that *embeddings* are indexed (#2358)
chat: use search context by default (#2325)
Agent: enable source maps in `pnpm agent` (#2334)
change nls label to beta (#2351)
VS Code: Release 0.18.6 (#2349)
Remove mention of Free/Pro from marketplace (#2347)
Chat: Fix settings menu not opening on click (#2346)
Chat Context: Provide relative path as current file (#2344)
Chat: Fix chat panel titles (#2345)
Update the marketplace readme to match product features (#2280)
Agent: skip file system tests on Windows for now (#2341)
Agent: add test case to accept autocomplete (#2337)
Edit: Update the changelog with a bunch of missed fixes from the last release (#2340)
Custom Commands: Filter out insert and edit commands from chat input (#2339)
Chat: Fix cody icon font usage (#2336)
Agent: implement `vscode.workspace.fs` (#1716)
Autocomplete: remove stop sequences for dynamuc multliline completions (#2326)
Autocomplete: log raw error in the development env (#2323)
Autocomplete: fix invalid position (#2324)
Agent: enable source maps in tests (#2333)
Remove complete command from CLI (#2332)
update pr-auditor token (#2321)
Autocomplete: remove `scminput` from the autocomplete languages setting default value (#2322)
Chore: Skip flaky agent chat cancellation test (#2320)
Update walkthrough to match product features (#2279)
Clean up VS Code Extension Settings (#2278)
VSCode: Make embeddings errors visible, resume indexing on restart (#2265)
Add V2 telemetry to remaining Cody events (#2060)
Chat: Fix reset recipe (#2313)
Autocomplete: Don't show loading spinner when rate limited (#2314)
Fix rate limit number being displayed (#2312)
Chore: Remove some GHA `ifs` that didn't work (#2299)
VS Code: Release 0.18.5 (#2308)
Commands: Include /test (#2305)
telemetry-v2: fix splitSafeMetadata to generate acceptable type (#2273)
Edit: Fix doc command jumping unnecessarily (#2296)
Edit: Flush diffs on apply (#2304)
Edit: Fix malformed comments from doc command with selection (#2290)
Chat: Update welcome message (#2298)
Chat: Add tooltip to disabled chat model selector (#2294)
Edit: Do not scroll into view on complete (#2297)
Fix keyDown:Paste:clicked events (#2293)
remove rg-based local keyword context fetcher (#2295)
Simple chat: Bring back chat telemetry (#2291)
Settings: Remove the "Simple Chat Context" setting (#2286)
Update rate limit error wording for Cody Pro users (#2287)
Chat: Remove Chat Suggestions setting that no longer works (#2284)
Settings: Relabel "symf Context" as "Search Context" (#2285)
Chat: Add support for cody.chat.preInstruction in the new preamble (#2255)
use context.globalStorageUri for symf indexes (#2271)
Add cody-pro-jetbrains feature flag (#2274)
Chat: Edit button to rename history chats (#1818)
VS Code: Release 0.18.4 (#2268)
Do not await `showSetupNotification` (#2267)
VS Code: Release 0.18.3 (#2262)
Autocomplete: Add Experimental hot streak mode (#2118)
Disable gzip compression for SSE streams (#2251)
Only search relative paths when @-mentioning files in chat (#2241)
JetBrains: Fix missing context files in the chat response (#2211)
Chat: Update chat icon and transcript gradient (#2254)
Add a Chat Settings button in Chat panels (#2117)
Replace "Sign Out" with an account dialog (#2233)
VSCode: Local Embeddings should pick up initial access token (#2247)
VSCode: Fix local embeddings status for non-git workspaces, git repos w/out remotes (#2235)
Fix pre-release version numbers not being correctly detected (#2240)
Handle context file searching using forward slashes on Windows (#2215)
VS Code: Release 0.18.2 (#2234)
Update CHANGELOG.md (#2232)
Mark Upgrade/Usage links as dot-com only (#2219)
Update CHANGELOG.md (#2226)
plg: display errors when autocomplete rate limits trigger (#2135)
Search: Only show search instructions on hover or focus (#2212)
Fix "Release Notes" label & link for pre-releases in sidebar (#2210)
send sigkill to symf when extension exits (#2225)
Adding endpoint for fetching feature flag (#2204)
Fix symf index dir on Windows (#2207)
symf: support cancelling index (#2202)
Don't duplicate @-filenames when pressing tab if the whole string has been typed (#2218)
Allow dotfiles to be included in context files list (#2209)
Reset feature flags when switching through logins (#2182)
Add rate limit upgrade for code edits (#2201)
Fix cursor blink issue and ensure proper chat initialization synchronization (#2193)
VSCode: Do not parse Windows file paths as URIs (#2197)
VSCode: Send `embeddings/initialize` to the local embeddings controller (#2183)
Chat: Improve Pro upgrade CTA styles (#2175)
Update intro chat message to be clear about coding questions (#2187)
VS Code: Release 0.18.1 (#2177)
Autocomplete: Remove top_k when using temperature (#2178)
fix: chat show up in tree view on submit (#2171)
Fix rate limit messages for short time spans (#2152)
ensure error message makes it through to chat view (#2176)
Enable symf-based context for chat (cody.experimental.symfContext) (#2166)
Add missing changelogs (#2174)
Chat: Improve slash command heading padding (#2173)
chore: Bump up macOS e2e runner instance size (#2145)
chat: fix abort (#2159)
chat: always include selection in enhanced context (#2144)
VS Code: Release 0.18.0 (#2111)
support custom commands in simple chat (#2153)
Chat: update embeddings and codebase identifiers (#2130)
chore: Speed up at-file-selection e2e test (#2146)
update enhance context display copy (#2086)
Fix isRateLimitError (#2151)
chore: Simplify new-history-ui e2e test to deflake (#2147)
Chat: Update message input placeholder to mention slash commands (#2142)
Chat: Reduce size of chats list blank copy (#2137)
Search: Style and UX improvements to the search panel (#2138)
Chat: Fix message input overlapping with enhanced context button (#2141)
enable cody.experimental.simpleChatContext by default (#2120)
feat: display error in webview for simple chat (#2132)
Chat: Speed up chat panel debounce w/ trigger on leading edge too (#2126)
Link to new Cody feedback URL (#2113)
Chat: Fix infinite loop when searching for symbols (#2114)
fix: invert notification toggle logic (#2122)
chore(deps): update dependency stylelint to ^15.11.0 (#2119)
change: enable new chat and search UIs by default (#2079)
```

## Test plan
- test everything possible

### CODE REVIEW

**Comment by mkondratek** [comment]
It is impossible to test it right now b/c of the issue with the agent (PLG Rate limiting error messages are currently broken).

**Comment by mkondratek** [comment]
tested. works!

**Comment by exigow** [comment]
Can you briefly describe what changes have been made with this update / add this to commit msg? You mentioned that you have a script that prints Cody commits since the last version bump.

Ofc just asking; It doesn't block me in any way, but I think it would speed-up testing. I tried using GH [compare/](https://github.com/sourcegraph/cody/compare/), but it seems to work only for branches or tags.


EDIT: Aaah, compare is not working because e789043dbd6225db6236b69d420a5ec0d809893c is on not the same branch (main).

**Comment by mkondratek** [comment]
I updated the PR description with the commits list.

**Comment by exigow** [comment]
It seems that everything are working fine (except for the context issues which we are aware of), but I've noticed that we now have a massive amount of this in the logs, during normal usage:

```txt
2023-12-15 17:26:54,488 [  68629]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
```

On the main branch, this log only appears during the first launch of the project.

Should we be concerned about this?

**Comment by mkondratek** [comment]
> It seems that everything are working fine (except for the context issues which we are aware of), but I've noticed that we now have a massive amount of this in the logs, during normal usage:
> 
> ```
> 2023-12-15 17:26:54,488 [  68629]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
> ```
> 
> On the main branch, this log only appears during the first launch of the project.
> 
> Should we be concerned about this?

I guess it happens for repositories that are not indexed by Sourcegraph.

**Comment by exigow** [comment]
I'm verifying this on the [sourcegraph](https://github.com/sourcegraph/sourcegraph) repo, so it should be indexed by definition. :smile: Interestingly, the status icon indicates that the context has been correctly recognized.

image

```txt
2023-12-15 17:44:50,217 [ 184047]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:44:53,632 [ 187462]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:44:55,896 [ 189726]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:44:57,367 [ 191197]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:01,677 [ 195507]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:03,687 [ 197517]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:03,694 [ 197524]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:04,975 [ 198805]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:17,695 [ 211525]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:21,015 [ 214845]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:28,805 [ 222635]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:28,939 [ 222769]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:28,945 [ 222775]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:30,626 [ 224456]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:31,312 [ 225142]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:35,757 [ 229587]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:48,246 [ 242076]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:48,701 [ 242531]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:49,339 [ 243169]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:49,816 [ 243646]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
2023-12-15 17:45:50,294 [ 244124]   WARN - #c.s.c.a.CodyAgent - No Git repository for URI file:///home/exigo/projects/sourcegraph/
```

**Review by exigow — APPROVED** [review]
Looks like this problem existed before with the difference that the warnings were less verbose. 

The priority now is to switch from cherry-picking to `main`.

**Pull request merged**
