### PR TITLE
Replace CHANGELOG.md with hardcoded link to GitHub releases page

### LINKED ISSUE #57890: JetBrains: link to GitHub releases from plugin changelog
The release notes for our plugin inside IntelliJ currently look like this

Image

Previously, we manually updated CHANGELOG.md while sending PRs, which was laborious and error prone because it was easy to forget to update the changelog. Now, we GitHub releases instead where we can auto-generate the list of merged pull requests, and we can manually write a dedicated "Highlights" section. We should therefore link to the GitHub releases page in the "What's new" page in IntelliJ

### PR DESCRIPTION
**Pull request by exigow**
Fixes: https://github.com/sourcegraph/sourcegraph/issues/57890

### Test plan

* Install plugin and open "What's New"
* Verify: description links to GitHub

### Demo

image

### CODE REVIEW

**Comment by exigow** [comment]
Side note: please be aware that "What's New" content may change automatically

Explanation & fix: https://github.com/sourcegraph/jetbrains/pull/74

**Review by Sa1to — APPROVED** [review]
LGTM

**Comment by pkukielka** [comment]
Won't that cause linking to the wrong release notes?
E.g. in your example you have nightly version installed but the latest one pointeb by `https://github.com/sourcegraph/jetbrains/releases` does not point to nightly ones.
@exigow

**Comment by exigow** [comment]
Thanks for noticing this!

You are correct, but the screenshot contains an outdated nightly version. This is fixed in my last PR with additional explanation (https://github.com/sourcegraph/jetbrains/pull/74).

AFAIK we don't have plans for regular nightly release notes, except for special occasions. I think we don't need to distinct nightly releases from stable releases.

**Review by olafurpg — COMMENTED** [review]
Great fix! Simple and gets the job done

**Pull request merged**
