### PR TITLE
feat(llm): add support for local Ollama models

### LINKED ISSUE #1159: feedback: Ollama support
### Installation Information

N/A

### Share your feedback

https://sourcegraph.com/blog/local-code-completion-with-ollama-and-cody

I would like to use Ollama with Cody for Jetbrains IDEs

### Additional context (logs, images, etc)

_No response_

### PR DESCRIPTION
**Pull request by abeatrix**
CLOSE https://github.com/sourcegraph/jetbrains/issues/1159 & https://linear.app/sourcegraph/issue/CODY-942/feedback-ollama-support

Screenshot 2024-06-26 at 2 40 29 PM

Adds support for the Ollama LLM by:
- Adding an Ollama icon to the Icons.java file
- Adding a case for "Ollama" in the ChatModelsResponse.kt file to map to the Ollama icon

Also added instruction on how to set up Ollama to run with JetBrains in the README.md

## Test plan

Add Ollama logo for displaying Ollama models in the UI:

jetbrain_ollama_chat

### CODE REVIEW

**Review by mkondratek — APPROVED** [review]
lgtm but...

1. the failing CI - ignore the failing integration tests. I am working on it. Please rerun the CI - it should pass at some point

2. how does it work? is it presently possible to use local models? 😮

**Comment by abeatrix** [comment]
> 2\. how does it work? is it presently possible to use local models? 😮

@mkondratek Yes it does! I've updated the README to include the instructions on how to get that setup too! Feel free to give that a try and let me know if it doesn't work for you :D

**Comment by abeatrix** [comment]
@mkondratek i tried rerunning the failed jobs but no luck. Am i missing some steps?

**Comment by mkondratek** [comment]
> @mkondratek i tried rerunning the failed jobs but no luck. Am i missing some steps?

Hah, probably I have more powerful mouse 😅

**Pull request merged**
