### PR TITLE
Apply repository cleaning, limits to old chat history state

### LINKED ISSUE #1366: JetBrains: More than 10 repo appear when opening older chats having 10+ repo added in context.
### Cody Version

6.0-localbuild

### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0-localbuild)
Kotlin: 233.14015.106-IJ

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Login to Cody with Enterprise user
3. Go to Cody and open any older chat having 10+ repo in context

### Observed behavior:
More than 10 repo appear with `null` values 

### Expected behavior

There should be some restriction to prevent this behavior.

### Additional context

**Video link:**

https://drive.google.com/file/d/1vod7B155DEt8bKEZ8h-j6uf2blJrXBRC/view?usp=drive_link

### PR DESCRIPTION
**Pull request by dominiccooney**
Fixes #1366

## Test plan

Manually tested:

1. Sign into an Enterprise account
1. Pencil, add a repository
1. Ask Cody something in chat
1. Close IntelliJ
1. Open `/path/to/workspace/.idea/cody_history.xml` and search for the chat message. Change the `<remoteRepositories>` list to include nulls, duplicates, more than 10 repositories, etc. See below for an example.
1. Reopen IntelliJ, Cody, Chat History, open the chat.
1. Verify that only there are no duplicate repos, `null` does not appear, etc.

```xml
                <enhancedContext>
                  <enhancedContext>
                    <remoteRepositories>
                      <list>
                        <remoteRepository />
                        <remoteRepository />
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository />
                        <remoteRepository />
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="github.com/sourcegraph/cody" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="github.com/sourcegraph/emacs-cody" />
                        </remoteRepository>
                        <remoteRepository>
                          <codebaseName value="jdk" />
                        </remoteRepository>
                      </list>
                    </remoteRepositories>
                  </enhancedContext>
                </enhancedContext>
```

### CODE REVIEW

**Comment by sqs** [comment]
Thanks, @dominiccooney. Do you think this is related to the JSON-RPC change (since it was first spotted in the 6.0-localbuild in https://sourcegraph.slack.com/archives/C06GFD8GFCN/p1713820552328229)?

**Review by pkukielka — APPROVED** [review]
LGTM

**Comment by pkukielka** [comment]
@dominiccooney changes looks good but I do not think it fixes the linked issue fully.
Problem was that in past I think we had no limiter which would prevent user from adding more than 10 repositories.
Perhaps after your changes that bug is fixed, but it is still possible to load such state from the history.
I'm not sure what best handling of such situation would be.
In worst case we can just take first 10 repos from the list and call it a day.

**Comment by dominiccooney** [comment]
> Problem was that in past I think we had no limiter which would prevent user from adding more than 10 repositories.
> Perhaps after your changes that bug is fixed, but it is still possible to load such state from the history.
> I'm not sure what best handling of such situation would be.
> In worst case we can just take first 10 repos from the list and call it a day.

@pkukielka Yeah... I've updated this to validate the repo list and update the tree view to truncate it at 10.

> Do you think this is related to the JSON-RPC change (since it was first spotted in the 6.0-localbuild in https://sourcegraph.slack.com/archives/C06GFD8GFCN/p1713820552328229)?

@sqs It is unrelated.

**Review by mkondratek — APPROVED** [review]
looks good

**Comment by pkukielka** [comment]
> @pkukielka Yeah... I've updated this to validate the repo list and update the tree view to truncate it at 10.

@dominiccooney hm, I fail to see this in the diff.

**Comment by dominiccooney** [comment]
>> @pkukielka Yeah... I've updated this to validate the repo list and update the tree view to truncate it at 10.

> @dominiccooney hm, I fail to see this in the diff.

It is subtle but `resolveReposWithErrorNotification` `take`s to `MAX_REMOTE_REPOSITORY_COUNT`. So the repos pushed to the extension was limited to 10 before this change. But now that we `updateTree` with the result, we limit the tree to displaying 10 too.

**Comment by dominiccooney** [comment]
@pkukielka I reproduced the issue with setting remote repos for dotcom accounts.

The cause is remote repos saved in chats.

I've fixed the issue by checking whether the active account is a dotcom account or not before restoring.

Once we can write integration tests, it would be great to have a regression gauntlet of chat histories we can run.

**Pull request merged**
